### ISSUE TITLE
Default handler for 'submit' form[method="GET"]

### ISSUE THREAD

**Issue by kaheglar** [aurelia/history-browser#17]
The default behavior of [GET] form submit is generally equivalent to that of a link click. It would be nice to have a default handler for this also.

**Comment by EisenbergEffect** [comment]
So, are you saying that forms that have a method of "GET" on them, when submitted, should trigger a client-side navigation? Would that also mean packaging up the form values into a query string or something like that? I'm just trying to get a feel for what you are trying to accomplish here.

**Comment by kaheglar** [comment]
Yes, I'm saying that the default behavior of form submits should be to trigger client side navigation, as this would mimic normal form behavior. I would expect explicit form submit bindings to prevent default  and thus not trigger navigation.
As you say, the GET form submit handler would need to serialize the query string properties in order to build the full URL. A common use case would be a search form.
For consistency it would be nice to have a default handler for POST forms, but how that would be implemented is less clear and the practical benefits less compelling.

**Comment by bryanrsmith** [comment]
I don't disagree, but I suspect it's a fairly uncommon need. I'd rather keep the core libraries as lean as we can. I think this would make a great plugin. Does that sound reasonable?

**Comment by EisenbergEffect** [comment]
@bryanrsmith I agree with you. I'm going to close this issue in favor of keeping the core lean.
