### ISSUE TITLE
Can not open link in new tab using middle button.

### ISSUE THREAD

**Issue by aksyonov** [aurelia/history-browser#19]
After I configured router to use PushState I can not open link in new tab using middle button. But I can do it using Ctrl + left button click because of [this check](https://github.com/aurelia/history-browser/blob/1a67ae11885db085d6921f78e0ca69afb616c883/src/link-handler.js#L77). To fix it probably need to add check for [event.button](http://www.w3schools.com/jsref/event_button.asp).

**Comment by bryanrsmith** [comment]
Good call. Would you be willing to send a PR with that change?

**Comment by aksyonov** [comment]
@bryanrsmith, sure, please take a look at PR #20.
