### ISSUE TITLE
element with href + click/dblclick.trigger

### ISSUE THREAD

**Issue by tkhyn** [aurelia/history-browser#23]
Hello (again!),

I'm using `pushState=true` (as well as `hashChange=false` but it does not seem to have any influence) and have an element defined as follows:

``` html
<a href.bind="url" dblclick.trigger="dblclick()">Double-click me!</a>
```

(the same issue can be observed if you replace 'dblclick' by 'click').

I would expect that whenever there is a `click` (as a `dblcick` sends 2 `click`s anyway) event handler bound to the element, the event is ignored by the `DefaultLinkHandler` and the router does not step in.

However, whenever I double-click on the element, the router handles the event (twice!) AND `click()` is called.

As far as I understand in [getEventInfo](https://github.com/aurelia/history-browser/blob/master/src/link-handler.js#L65) it's now ignored only if there is a left click and the URL is relative or root-relative. A propsed addition would be to check for the presence of `click` event handlers on that element.

I have made a gist here: https://gist.run/?id=2fba7f5617dd490eef561a2c07c4f6b0

The workaround I'm using for now is to only use fully qualified URLs to 'confuse' getEventInfo, but I believe I'm raising a valid point that could be fixed!

**Comment by EisenbergEffect** [comment]
I'm not sure we can change this in any way that will be general purpose. To customize it for your needs you can implement a different link handler implementation and register that with the DI.

**Comment by tkhyn** [comment]
Ok, thanks for the answer and tip. It's not top priority right now but if I can come up with a way to avoid using absolute URLs everywhere I'll publish it there in case somebody else runs into the same issue.
