### ISSUE TITLE
Inconsistent return for BrowserHistory.prototype.navigate

### ISSUE THREAD

**Issue by uncttao** [aurelia/history-browser#26]
I'm submitting a bug report

**Library Version**: 1.0.0
**Operating System**: Windows Server 2012 R2 Datacenter
**Node Version**: 7.3.0
**NPM Version**: 3.9.0
**JSPM/Webpack Version**: N/A
**Browser**: all
**Language**: ESNext

**Current behavior**:
The method `navigate` in class `BrowserHistory` should always return `boolean` by contract(as indicated in its TypeScript source code). However, one path
```
if (trigger) {
  return this._loadUrl(fragment);
}
```
calls and returns `_loadUrl`, which may subsequently call and return `this.options.routeHandler`. This is problematic because as least given `aurelia-router v1.0.2`, `this.options.routeHandler` will be initialized with `AppRouter.prototype.loadUrl`, the return type of which is a `Promise`.

**Expected/desired behavior:**
`BrowserHistory.prototype.navigate` should always return either `boolean` or `Promise`, but not both.

**Comment by Alexander-Taran** [comment]
@twttao is it still relevant?
what is your use case ?

**Comment by davismj** [comment]
https://github.com/aurelia/router/pull/544
