### ISSUE TITLE
history.previousLocation property not in d.ts

### ISSUE THREAD

**Issue by ry8806** [aurelia/history-browser#27]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

in the typings for the history class (e.g. Router.history) - there is no property `previousLocation`

I was expecting this property to be part of the d.ts file, at the moment I'm forced to cast `Router.history` to `any` to get the previous location.

Was this purposefully omitted?

If this was not purposefully omitted, I'm happy to make the changes to bring this into the TypeScript API

**Comment by EisenbergEffect** [comment]
We'll definitely take a PR.

**Comment by Alexander-Taran** [comment]
Maybe not that needed after all...

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : Year } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by EisenbergEffect** [comment]
This is really more of an internal property used by the router, not so much part of the history implementation or api.
