### ISSUE TITLE
replaceState bug on Safari in html with base tag.

### ISSUE THREAD

**Issue by 3cp** [aurelia/history-browser#34]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
Safari latest | iOS  Safari latest

* **Language:**
N/A

**Current behavior:**
Strictly not aurelia bug, but a Webkit bug.
https://github.com/aurelia/history-browser/blob/b2150087d02502bb5ee6366295456f884472a8d6/src/index.js#L192

The replaceState doesn't work properly on Safari (on both macOS and iOS) when `<base href="..">` is in use. It manifested as malfunctioned browser back/forward buttons in aurelia app with pushState turned on. 
https://github.com/aurelia/router/issues/574

To reproduce the issue on Mac, create `index.html` file with content
```
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
    <base href="/">
  </head>
  <body></body>
</html>
```
Serve the static file with `http-server` in the file directory (npm install -g http-server).

Open `http://127.0.0.1:8080` with Mac Safari, do following in dev console (one by one, not in one shot).
```
history.pushState({}, "", "/one"); // browser url shows http://127.0.0.1:8080/one
history.replaceState({}, null, null); // or ({}, "", null) or ({}, "") or ({}, null)
history.pushState({}, "", "/two"); // browser url shows http://127.0.0.1:8080/two
history.back(); 
// oops, browser url shows http://127.0.0.1:8080 instead of http://127.0.0.1:8080/one
```

To bypass this Safari bug, you have to feed current url back to replaceState:
```
const url = document.location.pathname + document.location.search + document.location.hash;
history.replaceState({}, null, url); // or ({}, "", url)
```

**Expected/desired behavior:**

* **What is the expected behavior?**
Expect back/forward buttons on Safari to work.

* **What is the motivation / use case for changing the behavior?**
The proposed dirty fix is to bypass Webkit bug, maybe should only apply to Safari?

cc @jwx @davismj

**Comment by jwx** [comment]
I followed up on https://github.com/aurelia/router/issues/574#issuecomment-364392659 a bit and found a post on Apple's developer forum that seems to apply to this:

This issue behaves as intended based on the following:
This is by design. We fixed a security bug in iOS that abused pushState/replaceState.

As for the fix: As long as it doesn't mess things up for the other browsers, I think it's better to avoid specific browser code and just apply it for all of them.

**Comment by 3cp** [comment]
Great. I have not tested the fix on aurelia app with `<base href="/someroot">`, I will run through thorough test on combination of conditions on all the browsers I can find, then create a PR in next few days.

**Comment by 3cp** [comment]
@jwx the security issue in https://stackoverflow.com/questions/47145052/ios-11-1-securityerror-dom-exception-18-blocked-attempt-to-use-history-replac might be irrelevant.

Safari tries to block the abuse of replaceState with a new url to override current url.
Our use case is passing null to the url, doesn't look like having any security concern.

**Comment by jwx** [comment]
@huochunpeng Yeah, it might. On the other hand, it seems to work when passing the current url. So the implementation of the security feature might consider `null` to not be the same as current url...

**Comment by 3cp** [comment]
After all done, I will report a bug to webkit to see what they respond.

**Comment by davismj** [comment]
Rather than `document.location`, try this and see if it works:

`this.history.replaceState(state, null, this.location.href);`

**Comment by davismj** [comment]
I've confirmed this fix. Preparing now.

**Comment by 3cp** [comment]
For reference, new bug report to webkit.
https://bugs.webkit.org/show_bug.cgi?id=182678

**Comment by 3cp** [comment]
For record, [the bug on webkit](https://bugs.webkit.org/show_bug.cgi?id=182678) is now fixed by Apple. should land in Safari in near future.

**Comment by thanhtungka91** [comment]
I got the same issue as stackoverflow

> After post a form, I use pushState/replaceState to manipulate the history. Then when refresh, Chrome will send GET request to the new url, but Safari will send POST. Is it a BUG in Safafi? Anyone had met it before?

https://stackoverflow.com/questions/46933389/safari-send-post-request-when-refresh-after-pushstate-replacestate

It occurs only in safari.

**Comment by 3cp** [comment]
Sounds like a safari bug.

**Comment by 3cp** [comment]
@thanhtungka91 I cannot reproduce the bug. I, myself, use Safari for daily dev work. I have many post actions (ajax post with fetch api) that leads to new route, I could not reproduce the refresh bug.

Can you provide a repo for reproducing it?

If your post is a traditional post form request which reloads the whole page, and you mutate the url manually in app after it loads, I don't see why should not the browser try to post and reload when you do refresh.

**Comment by thanhtungka91** [comment]
@3cp thank you for the reply. 
yep, our post is a traditional form with post request by submitting action. I see that the replaceState with a new URL is successful if the user tries to reload the page by on click reload icon at the address bar. However, the request is still the 'POST' method while other browsers like chrome or firefox are working fine with 'GET'.

**Comment by 3cp** [comment]
Traditional form does not use replaceState to change url, the url in browser address bar is either the url of your post url, or a redirection set by the response of the post action.

When you try to reload that page (coming out of a post form submit), browser will warn you "do you want to re submit the form".

I tested with Safari v13.0.2 and Chrome v77, both work same for me.

1. post action directly renders a html page. Both browsers ask user to confirm re-submit form when manually reload.
2. post action redirects to another page (can have same url as the post action). Both browsers use GET to reload the page.

The code I use to test:
```js
const http = require('http');

const server = http.createServer((req, res) => {
  console.log(req.url + ' ' + req.method);

  if (req.url === '/') {
    res.writeHead(200, { 'Content-Type': 'text/html'});
    res.write(`<!doctype html><html><head></head><body>
      Hello
      <form action="/do" method="POST">
        <button type="submit">Try</button>
      </form>
      </body></html>`);

  } else if (req.url === '/do' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'text/html'});
    res.write(`<!doctype html><html><head></head><body>
      Not doing anything
      </body></html>`);
  } else if (req.url === '/do' && req.method === 'POST') {
    // Uncomment option 1 branch or option 2 branch

    // option 1: render directly

    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.write(`<!doctype html><html><head></head><body>
      Did
      </body></html>`);

    // option 2: redirect

    // res.writeHead(302, { Location: '/do'});
  }
  res.end();
});

server.listen(8000);
```

**Comment by thanhtungka91** [comment]
@3cp thank you for providing the code, here is [the video ](https://drive.google.com/file/d/1hD7HkiFhZHhU6PURcf_hU1wqsSOae7pC/view)which showed that safari still send post method after replacestates, other browsers are fine.

**Comment by 3cp** [comment]
Thx very much! Now I see what you mean "after replaceState". I will play around that, probably a Safari bug.

**Comment by 3cp** [comment]
Even if you `history.pushState({}, "", "/whatever");`, Safari still tries to honour original post request on the different url `/whatever`. I will try to fire a Safari ticket.

**Comment by 3cp** [comment]
Ticket is logged. https://bugs.webkit.org/show_bug.cgi?id=202963

**Comment by thanhtungka91** [comment]
@3cp  great! thank you for opening the ticket. Looking forward to the response from safari team.

**Comment by Bennett-Larson** [comment]
@3cp @thanhtungka91 Have either of you heard any updates? Or found a way around this problem? Seems the ticket hasn't even been assigned to anyone.

**Comment by 3cp** [comment]
Same as you. I saw no update.
