### ISSUE TITLE
navigateBack to route

### ISSUE THREAD

**Issue by brendonparker** [aurelia/history-browser#6]
I guess this is a sort of feature request. I would find it very useful to have an optional parameter to the `navigateBack` that traverse the history until a specific route is reached.

The use case would be a looping workflow application, where once the user reaches a certain point, you'd direct them back to start over.

Perhaps something resembling this:

``` javascript
router.navigateBack('targetroute');
```

Thoughts on this? If thought to be a worth-while enhancement, I can work on a pull request.

**Comment by bryanrsmith** [comment]
`navigateBack()` results in the same thing as if the user had clicked the 'back' button in their browser. Supporting a target route to navigate back to seems likely to cause very confusing browser history behavior.

Would your problem be solved by a breadcrumb feature, where we tracked the path that the user took through the application, and allowed you to navigate "back" to a previous step? The difference here would be that navigating to one of the bread crumb steps would add a new entry to the history stack instead of unwinding it. We've had some other requests for this feature, and will be investigating at some point.

**Comment by brendonparker** [comment]
Not sure I follow. With that approach, why wouldn't you just continue to use the router to navigate forward? I don't see why any additional feature would be necessary.

I guess what I am asking for is that the history would be _unwound_. I can see how this would be confusing, and I'm not suggesting people would use it all the time. But in scenarios where the user is doing a looping process, going from step to step, I think it will make sense.

Given the example below, where each block represents a _screen_ and step in the history stack.

![screen shot 2015-05-08 at 10 01 38 am](https://cloud.githubusercontent.com/assets/989122/7537822/873179e2-f569-11e4-9a9e-1e5e4d7c0ddb.png)

Part of the thought here is that once something is submitted, I wouldn't want them to go _back_ to it. That aside, if the user looped through that 5 times, to get back to the menu, they'd have to click back 20 times, as opposed to once.

I could see the argument for adding a button to the screen that just navigates them to the menu. However, if on android for example, and they happen to use android's back button, they'd have to back a bunch.

**Comment by brendonparker** [comment]
FWIW - here's a snippet that gets me what I want.

```
    navigateBackToRoute(route){

        if(!(route instanceof Array))
            route = [route];

        var self = this;
        var killsub = this.ea.subscribe('router:navigation:complete', info => {
            if(route.indexOf(self.router.currentInstruction.fragment) >= 0){
                killsub();
            } else {
                self.router.navigateBack();
            }
        });
        this.router.navigateBack();
    }
```

the route parameter can be one or more routes that you want keep back'ing until you reach. So far this has met my needs, and haven't had any issues.

**Comment by bryanrsmith** [comment]
I think this is a bit too specialized to include by default. It could be done with a plugin that replaces or augments the BrowserHistory class.
